### ISSUE TITLE
Relationship with "Foundation for Apps"

### ISSUE THREAD

**Issue by dbartholomae** [pineconellc/angular-foundation#244]
Hi there,

I recently realized that what this project wants to achieve is very similar to "Foundation for Apps". What are your thoughts on integrating the projects?
I am not part of that project, but I am sure, they would appreciate the help.

Best,
Daniel

**Comment by jbrowning** [comment]
That's a good question. Our project came out before Foundation for Apps was announced and I was curious to see what they would do with that project. What they ended up releasing was a brand new set of styles and components and re-releasing the existing Foundation styles and components as Foundation for Sites. So, it turns out that our projects became complementary: use ours if you want to use the Foundation for Sites grid and styles, use theirs if you can use their new grid and styles in your project.

Thanks.
